using İNHERİTANCE.Classess;

Audi audi = new Audi();
audi.marka = "Audi";
audi.vites = "Otomatik";
audi.arababilgi(audi.marka, audi.vites);
Bmw bmw = new Bmw();
bmw.marka = "BMW";
bmw.vites = "Düz";
bmw.arababilgi(bmw.marka, bmw.vites);
Mercedes mercedes = new Mercedes();
mercedes.marka = "Mercedes";
mercedes.vites = "Otomatik";
mercedes.arababilgi(mercedes.marka, mercedes.vites);
Porsche porsche = new Porsche();
porsche.marka = "Porsche";
porsche.vites = "Otomatik";
porsche.arababilgi(porsche.marka, porsche.vites);
Togg togg = new Togg();
togg.marka = "Togg";
togg.vites = "Otomatik";
togg.arababilgi(togg.marka, togg.vites);
Toyota toyota = new Toyota();
toyota.marka = "Toyota";
toyota.vites = "Düz";
toyota.arababilgi(toyota.marka, toyota.vites);
